prepare for GUI node selection; prefer global node if newer
ethereum/ethereum-client-binaries pull request #13
Opened 2017-04-13 17:22 UTC by luclu

See https://github.com/ethereum/mist/pull/2144

2017-04-20 14:51 UTC, hiddentao requested changes
Good ideas, but we mustn't hardcode this logic. Need to refactor to keep things flexible. Let me know if you'd me to have a go at doing this.

2017-04-20 14:51 UTC, hiddentao commented on src/index.js
> +        var version = output.stdout.match(/\d+\.\d+\.\d+/)[0];
We should not be hardcoding version checks. The `sanityCheck.output` configuration key is meant to contain the output that needs to checked for.

2017-04-20 14:51 UTC, hiddentao commented on src/index.js
> +      if (version && semver.lt(version, client.version)) {
We should not be hardcoding this semver check. We should instead refactor the sanity check configuration system such that such logic can be easily represented. I would recommend adding a `versionCommand` config parameter which specifies the CLI arguments to use in order to obtain binary version. Then we can do this semver check.

2017-04-20 15:19 UTC, luclu commented on src/index.js
> +      if (version && semver.lt(version, client.version)) {
You are right, that would be better. 

Though, I can only think of using `stdout.match(/\d+\.\d+\.\d+/)[0]` for the version string hoping that every `<node> [--]version` will have its version as the first semantic version string in the output. 

Eventually the haystack-method is fine, but then a method to retrieve the system node's version via a regex in the `clientBinaries.json` might bring a bit more flexibility.

Alternatively we could omit the version checking and supply an optional boolean `--uselocalnode` quite similar to `--gethpath`.

What do you think?

2017-04-20 15:20 UTC, luclu commented
You are right, that would be better. 

Though, I can only think of using `stdout.match(/\d+\.\d+\.\d+/)[0]` for the version string hoping that every `<node> [--]version` will have its version as the first semantic version string in the output. 

Eventually the haystack-method is fine, but then a method to retrieve the system node's version via a regex in the `clientBinaries.json` might bring a bit more flexibility.

Alternatively we could omit the version checking and supply an optional boolean `--uselocalnode` quite similar to `--gethpath`.

What do you think?

2017-04-24 14:26 UTC, hiddentao commented
I think we could have a built-in type of sanity check that does the version check you require, so. e.g:

```js
{
    "clients": {
        "Geth": {
            "version": "1.5.5",
            "platforms": {
                "linux": {
                    "x64": {
                        "download": {
                            "url": "https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.5.5-ff07d548.tar.gz",
                            "type": "tar",
                            "sha256": "4f36d6df25c37eb33829407d8bf2cea209cc412b3443319e2430db18581c7c01",
                            "bin": "geth-linux-amd64-1.5.5-ff07d548/geth"
                        },
                        "bin": "geth",
                        "commands": {
                            /* Mandatory version check - ensuring binary is >= expected version */
                            "version": {
                                "args": "version",
                                "extract": <regex to extract version>
                            }
                            /* Optional sanity check to ensure binary is what we expect */
                            "sanity": {
                                "args": "some command",
                                "needle": <regex to search for>
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Thus it would call `geth version` and then check that the version output by the binary is >= to the version specified earlier on in the config. We could still keep the current sanity check system for additional checks.

2018-03-16 22:14 UTC, closed without merging